export const linkConstants = {
  sanpham: "/san-pham-kia",
  sorento_hybrid: "/kia-sorento-hybrid",
  tragop: "/tra-gop",
  tintuc: "/tin-tuc/tin-tuc-chung",
  uudai: "/tin-tuc/uu-dai",
  sukien: "/tin-tuc/su-kien",
  thongtinxe: "/tin-tuc/thong-tin-xe",
  dichvu: "/gioi-thieu-chung",
  suachua: "/sua-chua-chung",
  baoduong: "/bao-duong-dinh-ky",
  baohanh: "che-do-bao-hanh",
  lienhe: "/lien-he",
  giaxe: "/gia-xe-kia",
  brochure: "/tai-brochure",
  laithu: "dang-ky-lai-thu",
};
